name: Release new version

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-latest, image: ubuntu:20.04 }
          - { target: x86_64-unknown-linux-gnu,  os: ubuntu-latest, image: ubuntu:20.04 }
          - { target: aarch64-apple-darwin,      os: macos-latest                       }
          - { target: x86_64-apple-darwin,       os: macos-13                           }
          - { target: x86_64-pc-windows-msvc,    os: windows-latest                     }
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image || '' }}
      options: --privileged
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set the version
        shell: bash
        run: sed "s/development/$GITHUB_SHA/g" crates/static-analysis-kernel/src/constants.rs > bla && rm crates/static-analysis-kernel/src/constants.rs && mv bla crates/static-analysis-kernel/src/constants.rs

      - name: Build Rust binaries
        run: |
          cargo build --release --target ${{ matrix.target }} --bin datadog-static-analyzer
          cargo build --release --target ${{ matrix.target }} --bin datadog-static-analyzer-git-hook
          cargo build --release --target ${{ matrix.target }} --bin datadog-static-analyzer-server

      - name: Zip Rust binaries
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          zip -j datadog-static-analyzer-${{ matrix.target }}.zip target/${{ matrix.target }}/release/datadog-static-analyzer
          zip -j datadog-static-analyzer-git-hook-${{ matrix.target }}.zip target/${{ matrix.target }}/release/datadog-static-analyzer-git-hook
          zip -j datadog-static-analyzer-server-${{ matrix.target }}.zip target/${{ matrix.target }}/release/datadog-static-analyzer-server

      - name: Zip Rust binaries (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          7z a datadog-static-analyzer-${{ matrix.target }}.zip target/${{ matrix.target }}/release/datadog-static-analyzer.exe
          7z a datadog-static-analyzer-git-hook-${{ matrix.target }}.zip target/${{ matrix.target }}/release/datadog-static-analyzer-git-hook.exe
          7z a datadog-static-analyzer-server-${{ matrix.target }}.zip target/${{ matrix.target }}/release/datadog-static-analyzer-server.exe

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            datadog-static-analyzer-${{ matrix.target }}.zip
            datadog-static-analyzer-git-hook-${{ matrix.target }}.zip
            datadog-static-analyzer-server-${{ matrix.target }}.zip
          if-no-files-found: error
          retention-days: 7

  release:
    name: Release on GitHub
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -lR
        working-directory: artifacts

      - name: Create release
        run: |-
          gh release create \
            versions.json \
            artifacts/datadog-static-analyzer*.zip
        env:
          GH_TOKEN: ${{ github.token }}
